<?php

namespace DarkRises\WebBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FanartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FanartRepository extends EntityRepository
{
	public function smallGallery($id)
    {
        $result1 = $this->getEntityManager()
            ->createQuery('select q FROM DarkRisesWebBundle:Fanart q where q.id in (SELECT p FROM DarkRisesWebBundle:Fanart p where p.id < :id order by p.id DESC) order by q.id ASC')
            ->setParameter('id', $id)
            ->setMaxResults(5)
        	->getResult();
    	
    	
       $result2 = $this->getEntityManager()
            ->createQuery('SELECT p FROM DarkRisesWebBundle:Fanart p where p.id > :id order by p.id ASC')
            ->setParameter('id', $id)
            ->setMaxResults(5)
        	->getResult();
    	
    	$arrayGallery = array();
        foreach(array(0 => $result1, 1 => $result2) as $small){
        	foreach($small as $s){
				$arrayGallery[] = array(
					'path' => "/".$s->getUploadDir()."/".$s->getId().$s->getPath(),
					'dir' => "/".strtolower(str_replace(" ", "",$s->getAutor()))."/".$s->getId()."/"
				);
			}
        }
    	return $arrayGallery;
    }
}